### ISSUE TITLE
Old project code

### ISSUE THREAD

**Issue by KobeNuyts** [jampez77/garage_door_sensor#1]
Hello, I found [this](https://arduino.stackexchange.com/questions/75704/what-are-the-best-gpio-pins-to-use-for-my-project) project online, and it's exactly what I need, but I can only find the new code with the [Output OC Adapter](https://www.amazon.co.uk/gp/product/B07XZKDFX9/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1), but I can't buy it where I live and sending it will get quite expensive.
So I waned to ask if u still got the old code with the 2 switches. And if you could maybe send it to me?
Thanks in advance and kind Regards Kobe

(Here is a picture by what I mean)
![afbeelding](https://user-images.githubusercontent.com/102762606/227538272-a5fc0896-f96e-4284-8570-0ff33951d94f.png)

**Comment by jampez77** [comment]
Hi, Thanks for getting in touch.

That was the initial code for this project which you should be able to access by looking at the [Initial Commit](https://github.com/jampez77/garage_door_sensor/commit/89c8b51d63178dfbede97bb17b9b4bf9a71264c7)

I should tell you though that the project has always connected to the [Output OC Adapter](https://www.amazon.co.uk/gp/product/B07XZKDFX9/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1) so it probably won't help you much.

**Comment by KobeNuyts** [comment]
Thanks for the help I'll try the code
